pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: install

- script: npm run lint
  displayName: 'Run linting'

- script: npm run build
  displayName: 'Transpile TS files'

# - script: npm run test:ci
#   displayName: 'Run Unit Tests'

# - task: PublishTestResults@2
#   inputs:
#     testRunner: JUnit
#     testResultsFiles: ./junit.xml
#   condition: succeededOrFailed()

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1